server:
  port: 8080
  error:
    include-stacktrace: always

#spring:
#  jpa:
#    show-sql: true

security:
  oauth2:
    client:
      access-token-validity-seconds: 1200 #20 Minutos
      scope: password
      client-id: shop
      client-secret: 1234

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gerenciadorestoque?useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
